version: '2'

services:

  quexs:
    image: registry.acspri.org.au/quexs:2.5.0
    ports:
      - 8080:80
    environment:
      QUEXS_DB_PASSWORD: example
      QUEXS_DB_HOST: mysql
      QUEXS_PORT: :8080

  mysql:
    image: registry.acspri.org.au/mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: example

