version: '2'

services:

  quexs:
    image: acspri/quexs:2.5.0
    ports:
      - 8080:80
    environment:
      QUEXS_DB_PASSWORD: example
      QUEXS_DB_HOST: mysqldb
      QUEXS_PORT: :8080
    networks:
      - limesurvey-docker_default
      - quexs

  mysqldb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - quexs

networks:
  limesurvey-docker_default:
     name: limesurvey-docker_default
     external: true
  quexs:
     driver: bridge
     name: quexs